version: '2'

services:
  drupal:
    image: drupal-w-mysql-cli
    container_name: drupal.app
    ports: 
      - "80:80"
    volumes:
      - ./var/www/html/sites:/var/www/html/sites
      # - /Users/thevinh/Library/Logs/drupal.app_log:/var/log
      - /Users/thevinh/bin/drush:/drush/drush
    links:
      - db
  db:
    image: mariadb:5
    container_name: drupal.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mkd
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: drupal754
    volumes:
      - /Users/thevinh/db_data/mariadb040417:/var/lib/mysql
      - /Users/thevinh/docker_things/entrypoint/mysql-docker-machine.sh:/mysql-docker-machine.sh:rw
    entrypoint: /mysql-docker-machine.sh