version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: img_built/Dockerfile_nodejs_quasar
    container_name: quasar
    ports:
      - "80:8080"
    volumes:
      - /Users/thevinh/Projects/quasar:/opt/app
    working_dir: "/opt/app"
    # command: "npm run dev"
