version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: img_built/Dockerfile_nodejs_quasar
    container_name: quasar
    ports:
      - "80:80"
    volumes:
      - data:/var/quasar
volumes:
  data:
